### ISSUE TITLE
Massive Geschwindigkeitsprobleme auf der Homepage

### ISSUE THREAD

**Issue by tmaier** [AGVM/www.agv-muenchen.de#209]
Die AGV-Homepage ist unendlich langsam seit ein paar Monaten.

Das kann per-se nicht an der Seite liegen. Technisch und inhaltlich ist es die gleiche Seite, wie am Anfang.

## Ich vermute folgende Ursachen:
1. Irgend ein Skript auf dem Server frisst unsere Performance. Das kann z.B. ein bösartiges Skript sein, dass wir uns durch eine alte und unsichere PHP-Version eingefangen haben.  
Wir verwenden bei der Kartenbuchung PHP 4.4.9 aus dem Jahr 2008.
2. Beim Updaten von Wordpress ist etwas schief gegangen und seitdem läuft ein Wordpress-Plugin amok
3. Die Server-Leistung, die durch 1&1 zur Verfügung gestellt ist zu wenig.

## ToDo (Kurzfristig)

Nach der Beendigung der MS Starnberg-Kartenbuchung

* [x] Backup des Servers
* [x] Alles vom Server löschen
* [x] Wordpress-Seite neu aufsetzen (plugins, Theme, content) und neu hoch laden
* [ ] Beobachten
* [x] Alte Inhalte wieder uploaden

## ToDo (Langfristig)

Wir brauchend die "dynamischen" features eines datenbankbasierten CMS wie Wordpress nicht. Deshalb ist eine Version 2 der Homepage in Entwicklung, die dateibasiert ist.

Vorteile
* Es kann kein Sicherheitsproblem durch eine dynamische Sprache entstehen
* Flexibler beim Anpassen der Seite
* Inhalte sind einfacher zum Backupen. Nur noch ein Dateiverzeichnis und nicht zusätzlich eine Datenbank
* Es ist einfacher möglich einen Workflow aufzubauen, bei dem jeder die Inhalte bearbeiten kann, diese aber erst nach Bestätigung durch einen der Administratoren online sind.

Der aktuelle Code befindet sich hier: https://github.com/AGVM/www.agv-muenchen.de/tree/master.

Es gibt auch eine Demo-Seite. Diese ist a) noch nicht gestaltet und b) beim ersten Aufruf immer langsam, da der Server extra gestartet wird: https://agv.herokuapp.com/

//cc @agv-gs @NiklasAltekamp @AGropp @mbergmann1324 @philcap @Schlux

**Comment by michaellohr** [comment]
Ich schließ diesen Thread mal, da er veraltet ist.
Durch die Updates von Wordpress und den Plugins hat sich die Performance um einiges verbessert.
Falls dieses Problem trotzdem weiterhin besteht, bitte ein neues Issue aufmachen.
