### ISSUE TITLE
Ball der Musen 2015

### ISSUE THREAD

**Issue by tmaier** [AGVM/www.agv-muenchen.de#230]
https://www.agv-muenchen.de/event/ball-der-musen-2015/?instance_id=1131

## ToDo

* [ ] Fotos vom Stiftungsfestball adH
* [x] Neue Texte
* [x] Link von 2014er auf aktuellen Ball setzen. https://www.agv-muenchen.de/event/ball-der-musen-2014/
* [x] www.ball-der-musen.de leitet auf das aktuelle Event weiter
* [x] Link auf Kartenbuchung
* [x] Text Anleitung Kartenbuchung
* [x] Facebook-Event erstellen und bei Event verlinken
* [x] Speisen- und Getränkekarte hochladen und verlinken
* [x] Sitzplätze 2. OG hochladen und verlinken

//cc @philcap

**Comment by AGropp** [comment]
Wie sieht es mit den Fotos aus?

**Comment by philcap** [comment]
Bild und Text sind nun in guthub raufgeladen.
Philipp

Am 14.02.2015 um 22:04 schrieb Alexander Gropp:

**Comment by AGropp** [comment]
Wer wollte sich denn darum kümmern, dass die Bilder auf der Website landen?

**Comment by agv-gs** [comment]
Lieber Herr Gropp,

da hat sich bis jetzt niemand „hier“ geschriehen. 

 

Mit freundlichen Grüßen

 

Monika Kunisch

Geschäftsführung

Philisterverband des AGV

Akademischer Gesangverein München e.V.

Ledererstraße 5, 80331 München

Tel.: (089) 223707, Fax: (089) 29161441

 <mailto:geschaeftsstelle@agv-muenchen.de> geschaeftsstelle@agv-muenchen.de

 <http://www.agv-muenchen.de> www.agv-muenchen.de

 

Von: Alexander Gropp [mailto:notifications@github.com] 
Gesendet: Montag, 16. März 2015 14:35
An: AGVM/www.agv-muenchen.de
Cc: agv-gs
Betreff: Re: [www.agv-muenchen.de] Ball der Musen 2015 (#230)

 

Wer wollte sich denn darum kümmern, dass die Bilder auf der Website landen?
